### ISSUE TITLE
DID I GET BLACKLISTED?

### ISSUE THREAD

**Issue by mttgo** [Concepto-AI/docs#3]
![image](https://github.com/Concepto-AI/docs/assets/107141059/127a4e51-8563-4064-a214-c9ab0221434a)
or is it just unclear that i have not signed u/ dont have an account

**Comment by leowilkin** [comment]
I'll check, but it might be that in resetting the authentication system you might need a new token.

**Comment by leowilkin** [comment]
Fixed
